// Static import of the backtest artifacts generated by `python -m Source.Backtest.run`.
// These JSON files live in public/data and are the single source of truth for the site.
import summary from "@/public/data/summary.json";
import horizons from "@/public/data/horizons.json";
import strategies from "@/public/data/strategies.json";
import thresholdSweep from "@/public/data/threshold_sweep.json";
import decile from "@/public/data/decile.json";
import yearly from "@/public/data/yearly.json";
import attention from "@/public/data/attention.json";
import walkforward from "@/public/data/walkforward.json";
import price from "@/public/data/price.json";
import training from "@/public/data/training.json";
import features from "@/public/data/features.json";

export interface Summary {
  ticker: string;
  date_start: string;
  date_end: string;
  n_trading_days: number;
  n_samples: number;
  split: { train: number; val: number; test: number };
  n_features: number;
  horizons: number;
  lookback: number;
  mean_auc: number | null;
  mean_ic: number | null;
  primary_horizon: number;
  strategy_sharpe_net: number;
  strategy_total_return: number;
  strategy_max_drawdown: number;
  transaction_cost_bps: number;
  slippage_bps: number;
  total_cost_bps: number;
  use_sentiment: boolean;
  model: Record<string, number>;
  walk_forward_mean_sharpe: number | null;
}

export interface HorizonRow {
  horizon: number;
  auc: number;
  accuracy: number;
  baseline: number;
  class_balance_up: number;
  ic: number;
  p_value: number;
}

export interface StrategyReport {
  mode: string;
  sharpe_net: number;
  sharpe_gross: number;
  mean_return: number;
  total_return: number;
  max_drawdown: number;
  avg_exposure: number;
  n_trades: number;
  hit_rate: number;
  equity_curve: number[];
}

export const data = {
  summary: summary as Summary,
  horizons: horizons as HorizonRow[],
  strategies: strategies as Record<string, StrategyReport>,
  thresholdSweep: thresholdSweep as { threshold: number; sharpe: number; trade_freq: number }[],
  decile: decile as { decile: number; mean_return: number }[],
  yearly: yearly as { year: number; sharpe: number; n: number }[],
  attention: attention as { days_back: number; weight: number }[],
  walkforward: walkforward as {
    fold: number;
    train_size: number;
    test_size: number;
    sharpe_net: number;
    total_return: number;
    max_drawdown: number;
    auc_h20: number;
  }[],
  price: price as { date: string; close: number }[],
  training: training as { loss: number[]; val_loss: number[]; auc: number[]; val_auc: number[] },
  features: features as string[],
};

export const fmtPct = (x: number, d = 1) => `${(x * 100).toFixed(d)}%`;
export const fmtNum = (x: number, d = 3) => x.toFixed(d);
export const fmtSigned = (x: number, d = 3) => `${x >= 0 ? "+" : ""}${x.toFixed(d)}`;
